name: Maven Tests

on:
  workflow_dispatch: # Permite la ejecución manual del workflow
    inputs:
      tag: # Input para el tag
        description: 'Tag to execute' # Descripción del input
        required: true # El input es obligatorio
        default: '@Tests' # Valor por defecto del tag

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Actualización a la última versión compatible con Node.js 20

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Actualización a la última versión compatible con Node.js 20
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4 # Actualización a la última versión compatible con Node.js 20
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn clean test -Dcucumber.options="--tags ${{ github.event.inputs.tag }}"
